[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson@^7.0.4
    # SD is part of the ESP32 Arduino core — no extra entry needed

build_flags =
    -DCORE_DEBUG_LEVEL=0
